version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: always

    environment:
      POSTGRES_DB: Ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: